name: CI

on:
  push:
    branches:
      - main
    paths:
      - "Node_JS/Homework_12/**"
  pull_request:
    branches:
      - main
    paths:
      - "Node_JS/Homework_12/**"

jobs:
  docker_compose_and_test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies (if needed for any pre-steps, can usually be skipped in Docker context)
      - name: Install dependencies
        working-directory: ./
        run: npm install

      # Step 3: Set up and run Docker Compose
      - name: Set up and run Docker Compose
        run: docker compose up -d --wait

      # Step 4: Run linting
      - name: Run lint
        working-directory: ./
        run: npm run lint

      # Step 5: Run tests
      - name: Run tests
        working-directory: ./
        run: npm test -- --coverage

      # Step 6: Clean up Docker Compose
      - name: Shut down Docker Compose
        run: docker compose down
