name: CI

on:
  push:
    branches:
      - main
    paths:
      - "Homework_12/**"
  pull_request:
    branches:
      - main
    paths:
      - "Homework_12/**"

jobs:
  docker_compose_and_test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Set up Docker Compose
      - name: Build and start Docker Compose services
        run: |
          cd Homework_12/ByteWars
          docker-compose up -d --build

      # Step 4: Run linting
      - name: Run lint
        run: |
          cd Homework_12/ByteWars
          docker-compose exec -T server npm run lint

      # Step 5: Run tests
      - name: Run tests
        run: |
          cd Homework_12/ByteWars
          docker-compose exec -T server npm test -- --coverage

      # Step 6: Clean up Docker Compose
      - name: Shut down Docker Compose
        run: |
          cd Homework_12/ByteWars
          docker-compose down
